### ISSUE TITLE
Question about the evaluation results with the pretrained weights

### ISSUE THREAD

**Issue by TaNo0** [drinkingcoder/FlowFormer-Official#22] opened 2022-09-28 06:48 UTC
Thanks for your outstanding work.
I have a question about the evaluation results with the weight of C+T training (i.e., things.pth). With the default command as follows, 
python evaluate_FlowFormer_tile.py --eval sintel_validation
python evaluate_FlowFormer_tile.py --eval kitti_validation
it obtains the EPE of [0.939294, 2.329442] on Sintel, which matches the reported results (clean 0.94, final 2.33). However, the results on KITTI are [4.531271, 15.322450], which seems to drop a lot (compared with the scores of [4.09† 14.72†] in the paper). Do I miss something for KITTI evaluation?

![image](https://user-images.githubusercontent.com/18069796/192707835-cccefe8f-3643-48d7-8b29-17265a211788.png)

**Comment by drinkingcoder** [comment] 2022-10-18 07:21
Excuse me for the late reply. The model used in KITTI training set evaluation is FlowFormer# as introduced in our [supplementary](https://drinkingcoder.github.io/publication/flowformer/images/FlowFormer-supp.pdf). The original model is lost because NVIDIA has been attacked by hackers, which makes the devices that store my models locked :face_with_spiral_eyes:. We re-train models to reproduce the results. The results are [4.09, 14.51], slightly better than the numbers reported in our paper. We will update the corresponding information ASAP!

**Comment by drinkingcoder** [comment] 2022-10-19 03:48
The new model and evaluation scripts have been updated :partying_face:. Please check it.

**Comment by DQiaole** [comment] 2022-10-26 13:13
Hello~
I install the environment following the readme.md and tested the results on the KITTI training set with the latest code by the following command:
```
python evaluate_FlowFormer_tile.py --eval kitti_validation --model checkpoints/things_kitti.pth
```
but the results I get is [5.30, 15.10], I have no idea about this.  Do I miss something for KITTI evaluation?

![image](https://user-images.githubusercontent.com/49903017/198033638-2b3d206d-b0e5-4e8b-9ff9-551317e48f65.png)

Besides, can you repreduce the results on KITTI @TaNo0?

**Comment by drinkingcoder** [comment] 2022-10-27 07:35
The code has been updated again. Please check it. It should work now.

**Comment by DQiaole** [comment] 2022-10-27 07:47
Thank you for your qucik reply. I can successfully reproduce the resutls now.

**Comment by drinkingcoder** [comment] 2022-10-27 07:50
:partying_face: I can close this issue now.

**Closed by drinkingcoder** 2022-10-27 07:50 UTC
